### ISSUE TITLE
Logout mulfunctions

### ISSUE THREAD

**Issue by mwalughabura** [tunapanda/funzo-app#28] opened 2016-04-20 05:39 UTC
- When user logs out there are some sort of folders and links appear on the screen and looks scary for the users.

- Without exiting the app and getting into it again you can't swiftly get inside the app using the same or another account.

**Comment by Jakeii** [comment] 2016-04-20 15:57
this is a duplicate of #17 

thanks!

**Closed by Jakeii** 2016-04-20 15:57 UTC
Labels: bug
